# Generated by Django 4.2.3 on 2023-07-27 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studytracker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectInvite',
        ),
    ]
