# Generated by Django 4.2 on 2023-08-14 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studytracker', '0004_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
    ]
